apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce   # Tylko jeden pod może tu pisać naraz (logiczne dla SQL)
  resources:
    requests:
      storage: 2Gi    # Rozmiar dysku
