apiVersion: v1
kind: Service
metadata:
  name: mysql-service   # <--- TO BĘDZIE NAZWA HOSTA DLA FLASKA
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP       # Domyślny, bezpieczny, tylko wewnątrz
