apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1           # Bazy SQL (Master) zazwyczaj trzymamy pojedynczo (bez klastrowania na start)
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0   # Lub mysql:5.7 (zależy co lubisz)
        ports:
        - containerPort: 3306
        env:
        # Konfiguracja MySQL przez zmienne środowiskowe (mapowane z Secreta)
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-password
        # Montowanie dysku (To sprawia, że dane przeżyją restart)
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc1
          apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1           # Bazy SQL (Master) zazwyczaj trzymamy pojedynczo (bez klastrowania na start)
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0   # Lub mysql:5.7 (zależy co lubisz)
        ports:
        - containerPort: 3306
        env:
        # Konfiguracja MySQL przez zmienne środowiskowe (mapowane z Secreta)
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-name
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: db-password
        # Montowanie dysku (To sprawia, że dane przeżyją restart)
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
